#!/usr/bin/env bash

fresh freshshell/fresh bin/fresh --bin

fresh config/flameshot.ini --file="$HOME"/.config/flameshot/flameshot.ini

AWS_FILE=config/aws.asc
if test -f "$AWS_FILE"; then
  fresh "$AWS_FILE" --file="$HOME"/.config/aws/config --filter="gpg --quiet --batch --no-tty --decrypt"
fi
