[base]
depends = [
  "git",
  "gpg",
  "zsh",
]

[git.files]
"config/gitconfig" = "~/.config/git/config"

[gpg.files]
"config/gpg.conf" = "~/.gnupg/gpg.conf"
"config/gpg-agent.conf" = "~/.gnupg/gpg-agent.conf"

[zsh.files]
"config/zshrc" = "~/.zshrc"
