[base]
depends = [
  "flameshot",
  "git",
  "gpg",
  "i3",
  "rofi",
  "topgrade",
  "xinit",
  "zsh",
]

[work]
depends = [
  "base",
  "mysql",
]

[flameshot.files]
"config/flameshot.ini" = "~/.config/flameshot/flameshot.ini"

[git.files]
"config/gitconfig" = "~/.config/git/config"

[gpg.files]
"config/gpg.conf" = "~/.gnupg/gpg.conf"
"config/gpg-agent.conf" = "~/.gnupg/gpg-agent.conf"

[i3.files]
"config/i3config" = "~/.config/i3/config"
"config/i3status-rs" = "~/.config/i3status-rs/config.toml"

[mysql.files]
"config/my.cnf" = "~/.my.cnf"

[rofi.files]
"config/rofi.rasi" = "~/.config/rofi/config.rasi"

[topgrade.files]
"config/topgrade.toml" = "~/.config/topgrade.toml"

[xinit.files]
"config/xinitrc" = "~/.config/X11/xinitrc"

[zsh.files]
"config/zshrc" = "~/.zshrc"
