[base]
depends = [
  "git",
  "gpg",
  "i3",
  "zsh",
]

[work]
depends = [
  "base",
  "mysql",
]

[git.files]
"config/gitconfig" = "~/.config/git/config"

[gpg.files]
"config/gpg.conf" = "~/.gnupg/gpg.conf"
"config/gpg-agent.conf" = "~/.gnupg/gpg-agent.conf"

[i3.files]
"config/i3config" = "~/.config/i3/config"
"config/i3status-rs" = "~/.config/i3status-rs/config.toml"

[mysql.files]
"config/my.cnf" = "~/.my.cnf"

[zsh.files]
"config/zshrc" = "~/.zshrc"
